spring.application.name=nexus-auth
server.port=8084
server.address=0.0.0.0

# Database Configuration (NOVO BANCO)
spring.datasource.url=jdbc:postgresql://db.runvomspyktphgzgmina.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=qKJKJqTBJTEXvBbv
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP Pool Configuration
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

# JPA / Hibernate Configuration (Cria tabelas automaticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# JWT (HARDCODED)
jwt.secret=YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXpBQkNERUY=
jwt.expiration=3600000
jwt.refresh.expiration=604800000

# Logging
logging.level.org.springframework.web=INFO
logging.level.com.leandro.nexus_auth=DEBUG

# Email (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sistemanexusfinance@gmail.com
spring.mail.password=wzosnkrmxtzcmily
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Mercado Pago - PRODUÇÃO
mercadopago.access.token=APP_USR-5376893005432366-011111-a325728322a2232bfb91b9c811c6619a-213331101
mercadopago.public.key=APP_USR-471ad784-e4c5-465e-946c-2d1283d2803a
mercadopago.webhook.secret=ff26c53111071484119be3a94d5d753a06793c6782a6d4e35c22d1f54d38bfdd
