spring.application.name=nexus-auth
server.port=8084
server.address=0.0.0.0
# Conexao com Banco de Dados (HARDCODED)
spring.datasource.url=jdbc:postgresql://db.nsqiojozinlwfjdtexkz.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=qKJKJqTBJTEXvBbv
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT (HARDCODED)
jwt.secret=YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXpBQkNERUY=
jwt.expiration=3600000
jwt.refresh.expiration=604800000

# Email (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sistemanexusfinance@gmail.com
spring.mail.password=wzosnkrmxtzcmily
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# Sentinel
app.sentinel.url=https://sistema-sentinel-api.fly.dev/api/v1/sentinel